var JASMINE_PATH = "../ext/jasmine"

script(JASMINE_PATH + "/src/html/TrivialReporter.js")

script(JASMINE_PATH + "/spec/suites/BaseSpec.js")
script(JASMINE_PATH + "/spec/suites/CustomMatchersSpec.js")
script(JASMINE_PATH + "/spec/suites/EnvSpec.js")
script(JASMINE_PATH + "/spec/suites/ExceptionsSpec.js")
script(JASMINE_PATH + "/spec/suites/JsApiReporterSpec.js")
script(JASMINE_PATH + "/spec/suites/MatchersSpec.js")
script(JASMINE_PATH + "/spec/suites/MockClockSpec.js")
script(JASMINE_PATH + "/spec/suites/MultiReporterSpec.js")
script(JASMINE_PATH + "/spec/suites/NestedResultsSpec.js")
script(JASMINE_PATH + "/spec/suites/PrettyPrintSpec.js")
script(JASMINE_PATH + "/spec/suites/ReporterSpec.js")
script(JASMINE_PATH + "/spec/suites/RunnerSpec.js")
script(JASMINE_PATH + "/spec/suites/QueueSpec.js")
script(JASMINE_PATH + "/spec/suites/SpecSpec.js")
script(JASMINE_PATH + "/spec/suites/SpecRunningSpec.js")
script(JASMINE_PATH + "/spec/suites/SpySpec.js")
script(JASMINE_PATH + "/spec/suites/SuiteSpec.js")
script(JASMINE_PATH + "/spec/suites/TrivialReporterSpec.js")
script(JASMINE_PATH + "/spec/suites/WaitsForBlockSpec.js")
